format = """
$git_branch\
$git_status\
$python\
$nodejs\
$c\
$cpp\
$rust\
$java\
$golang\
$docker_context\
$kubernetes
$battery    $time	$cmd_duration
$os [$username](bold yellow)[ at ](white)[$hostname](green) [in](white) $directory\
$line_break\
$character
"""

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[battery]
full_symbol = "🔋"
charging_symbol = "⚡ "
discharging_symbol = "🔌 "

#[battery]
#full_symbol = "• "
#charging_symbol = "⇡ "
#discharging_symbol = "⇣ "

[[battery.display]]
threshold = 100

[time]
format = "[$time]($style)"
disabled = false

[username]
show_always = true
format = "[Yasin]($style)"

[hostname]
ssh_only = false
format = "[Debian]($style)"

[cmd_duration]                                   
format = '[$duration ]($style)'               
style = 'fg:bold green'                          
min_time = 500                                   
disabled = false

[c]
format = "[$symbol($version )]($style)"
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "
format = "[$symbol$context]($style)"

[elm]
symbol = " "

[golang]
symbol = " "
format = "[$symbol($version )]($style)"

[hg_branch]
symbol = " "

[java]
symbol = " "
format = "[$symbol($version )]($style)"

[memory_usage]
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"
symbol = " "

[os]
disabled = false

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "
format = "[$symbol($version )]($style)"

[python]
symbol = " "
format = "[$symbol($version )]($style)"
